name: campus_pal
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_gemini: ^2.0.1
  flutter_markdown: ^0.6.18+2
  lottie: ^2.7.0
  table_calendar: ^3.0.1
  shared_preferences: ^2.0.8
  path_provider: ^2.1.3
  path: ^1.8.0
  provider: ^6.0.5
  hive: ^2.0.0
  hive_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  hive_generator: ^1.1.0
  build_runner: ^2.0.0

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/lotties/
   - assets/lotties/food_pics/
   
